name: Build and run on alpine (native)
env:
  REGISTRY: ghcr.io

on:
  workflow_dispatch:
  push:

jobs:
  build-and-upload:
    runs-on: ubuntu-22.04
    steps:
      - uses: jirutka/setup-alpine@v1
        with:
          branch: v3.15

      - name: Install alpine build utils
        id: install-deps
        run: |
          apk add --update alpine-sdk make git bash go
        shell: alpine.sh --root {0}

      - name: Check out repository
        id: checkout
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # tag=v3.1.0
        with:
          ref: ${{ github.head_ref }}

      - name: Build apko
        id: build-apko
        run: |
          make apko install
        shell: alpine.sh {0}

      - name: Build apko example
        id: build-example
        run: |
          apko build examples/alpine-base.yaml alpine:local alpine.tar
        shell: alpine.sh {0}

      - name: Upload Artifact 'alpine.tar'
        id: upload-artifact
        uses: actions/upload-artifact@v2
        with:
          name: alpine
          path: alpine.tar
