name: Build apko example

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        id: checkout
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # tag=v3.1.0
        with:
          ref: ${{ github.head_ref }}

      - uses: chainguard-dev/actions/apko-build@main
        with:
          config: examples/alpine-base.yaml
          tag: leongross/apko:latest
          image_refs: foo.images
